#!/usr/bin/env sh
export LD_LIBRARY_PATH=/usr/local/mono-2-6-p1/lib:$LD_LIBRARY_PATH
export PATH=/usr/local/ironruby/bin:/usr/local/mono-2-6-p1/bin:$PATH
export PKG_CONFIG_PATH=/usr/local/mono-2-6-p1/pkgconfig
export MONO_PATH=/usr/local/mono-2-6-p1
export MONO_LIB=/usr/local/mono-2-6-p1/lib
#export MERLIN_ROOT=$WORKSPACE/Merlin/Main
export MONO_SHARED_DIR=/tmp

rake bacon
