require File.dirname(__FILE__) + '/core_ext/string'
require File.dirname(__FILE__) + '/core_ext/system/string'
require File.dirname(__FILE__) + '/core_ext/system/type'
require File.dirname(__FILE__) + '/core_ext/class'
require File.dirname(__FILE__) + '/core_ext/module'