require File.dirname(__FILE__) + '/string'
require File.dirname(__FILE__) + '/system/string'
require File.dirname(__FILE__) + '/system/type'
require File.dirname(__FILE__) + '/class'
require File.dirname(__FILE__) + '/module'
require File.dirname(__FILE__) + '/object'